---
- name: block example
  hosts: all
  tasks:
    - name: install and conf
      block:
        - name: package needed by yum
          yum:
            name: yum-plugin-versionlock
            state: present
        - name: lock version of tzdata
          lineinfile:
            dest: /etc/yum/pluginconf.d/versionlock.list
            line: tzdata-2016j-1
            state: present
        when: ansible_distribution == "RedHat" # condition on block usage

    - name: upgrade DB
      block:
        - name: upgrade the db
          shell:
            cmd: /usr/local/lib/upgrade-database
      rescue: # if task in 'block' fails
        - name: revert the db upgrade
          shell:
            cmd: /usr/local/lib/revert-database
      always: # will always run
        - name: always restart the database
          service:
            name: mariadb
            state: restarted
