---
- hosts: all
  force_handlers: yes # will run handlers even if task(s) fail
  tasks:
    - name: Run user creation script
      shell: /usr/local/bin/create_users.sh
      register: command_result
      failed_when: "'Password missing' in command_result.stdout"
      # ^^^^^ can be vvvvv thanks to fail module
    - name: Report script failure
      fail:
        msg: "The password is missing in the output"
      when: "'Password missing' in command_result.stdout"
      
    - name: get credentials as "admin"
      shell: echo "{{ krb_admin_pass }}" | kinit -f admin
      changed_when: false # task will not report "changed" but "ok", or "failed"

      # force 'changed' report on condition
      - shell:
          cmd: /usr/local/bin/upgrade-database
        register: command_result
        changed_when: "'Success' in command_result.stdout"
        notify:
          - restart_database
