---
force_handlers: yes

- name: copy file template
  template:
    src: /var/lib/templates/file.conf.template
    dest: /etc/httpd/conf.d/file.conf
  notify: # will not run in this order
    - restart mysql
    - restart apache

# handlers will run once all tasks have processed
handlers: # will run in this order 
  - name: restart apache # will run just once, even if notified multiple times
    service:
      name: httpd
      state: restarted
    
  - name: restart mysql
    service:
      name: mariadb
      state: restarted
